brokerUrl=failover:(tcp://localhost:61616)?initialReconnectDelay=100&jms.useCompression=true
topic=eew.alg.dm.logs
user=elarms
password=53EqXqwJw46e
directory=/app/dm/run/logs
prefix=dm_
suffix=.log
lineLimit=500
sendInterval=10
waitMSec=500
verbose=0
