# decimod configuration for Decision Module (DM)

# File containing an integer id. Defaults to 1. Can be initialized before starti              ng the program.
EventIDFile             lastdmevent.id

# input messages. ActiveMQ login, password and IP address
AlgorithmUser           dm_algori_user
AlgorithmPassword       dm_algori_pass
AlgorithmURI            failover:(tcp://localhost:dm_tcp_port)

# Input topic group used by the contributing algorithms.
# For example, eew.alg.elarms.data, eew.alg.vs.data, eew.alg.onsite.data
AlgorithmTopic          eew.agg.*.data

# output messages. ActiveMQ login, password and IP address. This can be a differ              ent ActiveMQ
AlertUser               dm_alert_user
AlertPassword           dm_alert_pass
AlertURI                failover:(tcp://localhost:dm_tcp_port)

# Output topic. This topic is read by the UserDisplay program and other applicat              ion programs.
# See UserDisplay/app.properties: DMSubscriptionID
AlertTopic              eew.sys.dm.data

# All messages to stdout are also sent to this topic
LogURI                  failover:(tcp://localhost:dm_tcp_port)
LogTopic                eew.sys.dm.log

# read heartbeats from HeartbeatInTopic and forward to HeartbeatOutTopic
HeartbeatInTopic        eew.agg.*.hb
HeartbeatOutTopic       eew.sys.dm.hb

# the heartbeat name
HeartbeatSender         dm_heartbeat_name
HeartbeatOriginator     dm_heartbeat_name


# discard dm and algorithm events older than this.
DMEventTimeoutSecs      600
AlgEventTimeoutSecs     600

# event association criteria
# AssocMethod: 0 is undefined, 1 is epicenter, 2 is station
AssocMethod             1
# event association by epicenter criteria
MaxMisfit               2.0
MaxDistkmToEvent        100.0
MaxTimeToEvent          30.0
# event association by station criteria
MaxDistStnAssoc         50.0
MaxTimeStnAssoc         60.0
MinNumStnAssoc          3

# filter settings: An alert will only be sent if the DM likelihood is >= DmMinLi              kelihood
DmMinLikelihood         0.4

# algorithm events will be rejected if their attributes are outside of these lim              its
MinMagnitude            0.0
MaxMagnitude            9.0
MaxMagUncer             10.0
MaxLatUncer             10.0
MaxLonUncer             10.0
MinDepthKm              -5.0
MaxDepthKm              500.0
MaxDepthUncer           500.0
MaxOriginTimeUncer      60.0
MinLikelihood           0.0

# Send alerts only for events within one of the following regions, with a magnit              ude >= the region MinMag
Regions WC
WC_MinMag 3.5
WC_MinMMI 3.
WC_latlon 37.43,-117.76,39,-120,42,-120,42,-117,49,-117,50,-117,50,-128.1,47.995              91,-128.1,47.99591,-126.77735,45.35223,-125.93440,43,-126,42,-126,40,-126,34.5,-              121.25,31.5,-119.26405,31.5,-113.8930,34.5,-114,37.43,-117.76

# if DM gets an algorithm alert with magnitude X where X>6, then no alert will b              e issued until
# a 2nd algorithm reports an event with a magnitude greater than X-1.
TwoAlgMagnitude   10.0

FaultInfoMinMag 6.0

DMSystemName    dm

PublishChangesOnly true

AlgNames sa, eqinfo2gm

AlgCoreContributors sa

ForwardContributors eqinfo2gm-contour, eqinfo2gm-map

eqinfo2gm-contour.topic eew.sys.gm-contour.data
eqinfo2gm-map.topic eew.sys.gm-map.data

UseGMContour true

sa_alert_alone true
eqinfo2gm_alert_alone false

TimeThrottling true
TimeThrottlingValue 0.5

MagReportPrecision 1

UseRepublishThreshold true

CHANGE_THRESHOLD_MAG         0.10
CHANGE_THRESHOLD_MAG_UNCER   0.10
CHANGE_THRESHOLD_LAT         0.05
CHANGE_THRESHOLD_LAT_UNCER   0.05
CHANGE_THRESHOLD_LON         0.05
CHANGE_THRESHOLD_LON_UNCER   0.05
CHANGE_THRESHOLD_DEPTH       0.50
CHANGE_THRESHOLD_DEPTH_UNCER 1.00
CHANGE_THRESHOLD_OTIME       1.00
CHANGE_THRESHOLD_OTIME_UNCER 1.00
CHANGE_THRESHOLD_LKLHD       0.10
