---
# packages role variables
yum_groups_additional:
- "@development"
- "@system-admin-tools"
yum_groups_additional_state: present
yum_additional:
- apr-util-devel
- gcc-gfortran
- gvim
- imake
- lcov
- libgfortran
- nc
- xterm
yum_additional_state: present
install_lxml: true
install_requests: true
install_paho_mqtt: true
install_matplotlib: true
install_basemap: true
install_obspy: true

# etc_hosts role variable
etc_hosts_group: development_integration
