---
all:
  children:
    bk:
      hosts:
        eew-bk-test1.geo.berkeley.edu:
        eew-bk-test2.geo.berkeley.edu:
    ci:
      hosts:
        eew-ci-test1.gps.caltech.edu:
        eew-ci-test2.gps.caltech.edu:
    ci_alert:
      hosts:
        eew-ci-test-alert1.gps.caltech.edu:
        eew-ci-test-alert2.gps.caltech.edu:
    nc:
      hosts:
        eew-nc-test1.wr.usgs.gov:
        eew-nc-test2.wr.usgs.gov:
    nc_alert:
      hosts:
        eew-nc-test-alert1.wr.usgs.gov:
        eew-nc-test-alert2.wr.usgs.gov:
    uw:
      hosts:
        eew-uw-test1.ess.washington.edu:
        eew-uw-test2.ess.washington.edu:
    uw_alert:
      hosts:
        eew-uw-test-alert1.ess.washington.edu:
        eew-uw-test-alert2.ess.washington.edu:
