---
all:
  children:
    dev1:
      hosts:
        eew-bk-dev1.geo.berkeley.edu:
        eew-bk-dev2.geo.berkeley.edu:
        eew-ci-dev1.gps.caltech.edu:
        eew-nc-dev1.wr.usgs.gov:
        eew-uw-dev1.ess.washington.edu:
    bk:
      hosts:
        eew-bk-dev1.geo.berkeley.edu:
        eew-bk-dev2.geo.berkeley.edu:
    ci:
      hosts:
        eew-ci-dev1.gps.caltech.edu:
        eew-ci-dev3.gps.caltech.edu:
    nc:
      hosts:
        eew-nc-dev1.wr.usgs.gov:
        eew-nc-dev2.wr.usgs.gov:
    uw:
      hosts:
        eew-uw-dev1.ess.washington.edu:
        eew-uw-dev2.ess.washington.edu:
    dev1:
      hosts:
        eew-bk-dev1.geo.berkeley.edu:
        eew-ci-dev1.gps.caltech.edu:
        eew-nc-dev1.wr.usgs.gov:
        eew-uw-dev1.ess.washington.edu:
