---
#name: deploy  amq_dm directories
#hosts: local
# become: yes
 # become_user: localadmin
 # gather_facts: no  
  vars:
    folder: amq_dm
  tasks:
  - name: copy source folder to /home/feiwang/tests
    copy:
      src: /app/amq/run/{{ folder }}
      dest: /home/feiwang/tests/{{ folder }}
