---
all:
  children:
    bk:
      hosts:
        eew-bk-int1.geo.berkeley.edu:
        eew-bk-int2.geo.berkeley.edu:
    ci:
      hosts:
        eew-ci-int1.gps.caltech.edu:
        eew-ci-int2.gps.caltech.edu:
    ci_alert:
      hosts:
        eew-ci-int-alert1.gps.caltech.edu:
        eew-ci-int-alert2.gps.caltech.edu:
    nc:
      hosts:
        eew-nc-int1.wr.usgs.gov:
        eew-nc-int2.wr.usgs.gov:
    nc_alert:
      hosts:
        eew-nc-int-alert1.wr.usgs.gov:
        eew-nc-int-alert2.wr.usgs.gov:
    uw:
      hosts:
        eew-uw-int1.ess.washington.edu:
        eew-uw-int2.ess.washington.edu:
    uw_alert:
      hosts:
        eew-uw-int-alert1.ess.washington.edu:
        eew-uw-int-alert2.ess.washington.edu:
    alert:
      hosts:
        eew-ci-int-alert1.gps.caltech.edu:
        eew-ci-int-alert2.gps.caltech.edu:
        eew-nc-int-alert1.wr.usgs.gov:
        eew-nc-int-alert2.wr.usgs.gov:
        eew-uw-int-alert1.ess.washington.edu:
        eew-uw-int-alert2.ess.washington.edu:
    dbservers:
      hosts:
        eew-bk-int1.geo.berkeley.edu:
        eew-bk-int2.geo.berkeley.edu:
        eew-ci-int1.gps.caltech.edu:
        eew-ci-int2.gps.caltech.edu:
        eew-ci-int-alert1.gps.caltech.edu:
        eew-ci-int-alert2.gps.caltech.edu:
        eew-nc-int1.wr.usgs.gov:
        eew-nc-int2.wr.usgs.gov:
        eew-nc-int-alert1.wr.usgs.gov:
        eew-nc-int-alert2.wr.usgs.gov:
        eew-uw-int1.ess.washington.edu:
        eew-uw-int2.ess.washington.edu:
        eew-uw-int-alert1.ess.washington.edu:
        eew-uw-int-alert2.ess.washington.edu:
